# Generated by Django 4.2.1 on 2023-05-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='profile_picture',
        ),
    ]
