# Generated by Django 4.2.1 on 2023-05-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_price'),
        ('orders', '0002_userorder_date_userorder_description_userorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.offers'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
