# Generated by Django 4.2.1 on 2023-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
