# Generated by Django 4.2.1 on 2023-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_offer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Offers',
        ),
    ]
