# Generated by Django 4.2.1 on 2023-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_offer_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='images',
            field=models.ImageField(max_length=999, upload_to='offer_images'),
        ),
    ]
