# Generated by Django 4.2 on 2023-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_offers_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
